<a href="https://colab.research.google.com/github/MMBAYAR/Spring24_MIS356/blob/main/MIS356_W4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#  Numpy library and its use as linear algebra object storage

In [1]:
#. To install python libraries to this session
!pip install numpy

In [2]:
#. To import a python module fully to this session

import numpy

In [3]:
#. To import some sub module within a module to this session
#.   I am just importing numpy.array() function

from numpy import array

In [5]:
#. Creating a scalar in a numpy.array form
the_number = 50

In [6]:
[the_number]

[50]

In [7]:
numpy.array( [the_number] )

array([50])

In [8]:
#. Creating a vector in a numpy.array form
[ 50, 85, 310, 4, 16 ]

[50, 85, 310, 4, 16]

In [9]:
numpy.array( [ 50, 85, 310, 4, 16 ] )

array([ 50,  85, 310,   4,  16])

In [10]:
#. Creating a matrix in a numpy.array form
[
    [ 50, 85, 310, 4, 16 ],
    [ -2, 0.15, 2/3, 6, numpy.pi ],
    [ 0, .81, 1.15, 0, 0 ]
]

[[50, 85, 310, 4, 16],
 [-2, 0.15, 0.6666666666666666, 6, 3.141592653589793],
 [0, 0.81, 1.15, 0, 0]]

In [11]:
numpy.array( [
    [ 50, 85, 310, 4, 16 ],
    [ -2, 0.15, 2/3, 6, numpy.pi ],
    [ 0, .81, 1.15, 0, 0 ]
] )

array([[ 5.00000000e+01,  8.50000000e+01,  3.10000000e+02,
         4.00000000e+00,  1.60000000e+01],
       [-2.00000000e+00,  1.50000000e-01,  6.66666667e-01,
         6.00000000e+00,  3.14159265e+00],
       [ 0.00000000e+00,  8.10000000e-01,  1.15000000e+00,
         0.00000000e+00,  0.00000000e+00]])

In [12]:
matrix = numpy.array( [
    [ 50, 85, 310, 4, 16 ],
    [ -2, 0.15, 2/3, 6, numpy.pi ],
    [ 0, .81, 1.15, 0, 0 ]
] )

In [14]:
#  Retrieving the value pi by its row and columns indices
matrix[1,4]

3.141592653589793

In [17]:
#  Retrieving a column: 2nd column
matrix[:, 1]


array([85.  ,  0.15,  0.81])

In [20]:
#. Retrieving a row: 3rd row
matrix[2, :]


array([0.  , 0.81, 1.15, 0.  , 0.  ])

In [31]:
#. Slicing a matix: original: 3x5 / slice: the last two rows with the middle columns
#.   starts from row 2 and goes to the end
matrix[ 1: ]

array([[-2.        ,  0.15      ,  0.66666667,  6.        ,  3.14159265],
       [ 0.        ,  0.81      ,  1.15      ,  0.        ,  0.        ]])

In [34]:
#.   starts from column2 and goes to the 4th
matrix[ :, 1:3 + 1 ]

array([[8.50000000e+01, 3.10000000e+02, 4.00000000e+00],
       [1.50000000e-01, 6.66666667e-01, 6.00000000e+00],
       [8.10000000e-01, 1.15000000e+00, 0.00000000e+00]])

In [35]:
#.   get rows 2-3, columns 2-4:
matrix[ 1: , 1:3+1 ]

array([[0.15      , 0.66666667, 6.        ],
       [0.81      , 1.15      , 0.        ]])

negative indices mean counting from the right instead left

In [36]:
matrix[ 1: , 1:-2 + 1 ]

array([[0.15      , 0.66666667, 6.        ],
       [0.81      , 1.15      , 0.        ]])

In [39]:
#. Reshaping numpy arrays
#.   Transform matrix into a vector
matrix.shape

(3, 5)

In [42]:
matrix.reshape( 15,1 )

array([[ 5.00000000e+01],
       [ 8.50000000e+01],
       [ 3.10000000e+02],
       [ 4.00000000e+00],
       [ 1.60000000e+01],
       [-2.00000000e+00],
       [ 1.50000000e-01],
       [ 6.66666667e-01],
       [ 6.00000000e+00],
       [ 3.14159265e+00],
       [ 0.00000000e+00],
       [ 8.10000000e-01],
       [ 1.15000000e+00],
       [ 0.00000000e+00],
       [ 0.00000000e+00]])

In [43]:
matrix.reshape( -1, 1 )

array([[ 5.00000000e+01],
       [ 8.50000000e+01],
       [ 3.10000000e+02],
       [ 4.00000000e+00],
       [ 1.60000000e+01],
       [-2.00000000e+00],
       [ 1.50000000e-01],
       [ 6.66666667e-01],
       [ 6.00000000e+00],
       [ 3.14159265e+00],
       [ 0.00000000e+00],
       [ 8.10000000e-01],
       [ 1.15000000e+00],
       [ 0.00000000e+00],
       [ 0.00000000e+00]])

#. Using Pandas module to import datasets to a session

In [44]:
!pip install pandas

In [45]:
import pandas

In [46]:
#. I will call the auto.csv file to this session and transform into a pandas.DataFrame object
/content/Auto.csv

NameError: name 'content' is not defined

In [47]:
pandas.DataFrame(  )

Empty DataFrame
Columns: []
Index: []

In [52]:
df = pandas.read_csv( '/content/Auto.csv' )

In [49]:
type( pandas.DataFrame(  ) ) == type( pandas.read_csv( '/content/Auto.csv' ) )

True

In [53]:
df

mpg  cylinders  displacement horsepower  weight  acceleration  year  \
0    18.0          8         307.0        130    3504          12.0    70   
1    15.0          8         350.0        165    3693          11.5    70   
2    18.0          8         318.0        150    3436          11.0    70   
3    16.0          8         304.0        150    3433          12.0    70   
4    17.0          8         302.0        140    3449          10.5    70   
..    ...        ...           ...        ...     ...           ...   ...   
392  27.0          4         140.0         86    2790          15.6    82   
393  44.0          4          97.0         52    2130          24.6    82   
394  32.0          4         135.0         84    2295          11.6    82   
395  28.0          4         120.0         79    2625          18.6    82   
396  31.0          4         119.0         82    2720          19.4    82   

     origin                       name  
0         1  chevrolet chevelle malibu  
1         1          buick skylark 320  
2         1         plymouth satellite  
3         1              amc rebel sst  
4         1                ford torino  
..      ...                        ...  
392       1            ford mustang gl  
393       2                  vw pickup  
394       1              dodge rampage  
395       1                ford ranger  
396       1                 chevy s-10  

[397 rows x 9 columns]

In [54]:
#. write down the data titles (columns of a dataframe)

df.columns

Index(['mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'year', 'origin', 'name'],
      dtype='object')

In [55]:
#. the number entries/observations in the dataset

len( df )

397

In [57]:
#. descriptive statistics of the data

df.describe().T

count         mean         std     min     25%     50%     75%  \
mpg           397.0    23.515869    7.825804     9.0    17.5    23.0    29.0   
cylinders     397.0     5.458438    1.701577     3.0     4.0     4.0     8.0   
displacement  397.0   193.532746  104.379583    68.0   104.0   146.0   262.0   
weight        397.0  2970.261965  847.904119  1613.0  2223.0  2800.0  3609.0   
acceleration  397.0    15.555668    2.749995     8.0    13.8    15.5    17.1   
year          397.0    75.994962    3.690005    70.0    73.0    76.0    79.0   
origin        397.0     1.574307    0.802549     1.0     1.0     1.0     2.0   

                 max  
mpg             46.6  
cylinders        8.0  
displacement   455.0  
weight        5140.0  
acceleration    24.8  
year            82.0  
origin           3.0

In [58]:
df.skew()

<ipython-input-58-9e0b1e29546f>:1: FutureWarning: The default value of numeric_only in DataFrame.skew is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.skew()


mpg             0.456005
cylinders       0.522818
displacement    0.716282
weight          0.530989
acceleration    0.280818
year            0.013108
origin          0.919911
dtype: float64

In [59]:
df.kurtosis()

<ipython-input-59-c7edf97eb14c>:1: FutureWarning: The default value of numeric_only in DataFrame.kurt is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.kurtosis()


mpg            -0.517322
cylinders      -1.380668
displacement   -0.753441
weight         -0.790660
acceleration    0.445525
year           -1.178955
origin         -0.824815
dtype: float64

In [61]:
df.mode()

mpg  cylinders  displacement horsepower  weight  acceleration  year  \
0  13.0        4.0          97.0        150    1985          14.5  73.0   
1   NaN        NaN           NaN        NaN    2130           NaN   NaN   

   origin        name  
0     1.0  ford pinto  
1     NaN         NaN

In [63]:
df.origin.unique()

array([1, 3, 2])

In [64]:
#. Filter out the origin category 1:

df.origin == 1

0       True
1       True
2       True
3       True
4       True
       ...  
392     True
393    False
394     True
395     True
396     True
Name: origin, Length: 397, dtype: bool

In [66]:
#.   using a boolean mask to filter a dataframe
df[ (df.origin == 1) ]

mpg  cylinders  displacement horsepower  weight  acceleration  year  \
0    18.0          8         307.0        130    3504          12.0    70   
1    15.0          8         350.0        165    3693          11.5    70   
2    18.0          8         318.0        150    3436          11.0    70   
3    16.0          8         304.0        150    3433          12.0    70   
4    17.0          8         302.0        140    3449          10.5    70   
..    ...        ...           ...        ...     ...           ...   ...   
391  27.0          4         151.0         90    2950          17.3    82   
392  27.0          4         140.0         86    2790          15.6    82   
394  32.0          4         135.0         84    2295          11.6    82   
395  28.0          4         120.0         79    2625          18.6    82   
396  31.0          4         119.0         82    2720          19.4    82   

     origin                       name  
0         1  chevrolet chevelle malibu  
1         1          buick skylark 320  
2         1         plymouth satellite  
3         1              amc rebel sst  
4         1                ford torino  
..      ...                        ...  
391       1           chevrolet camaro  
392       1            ford mustang gl  
394       1              dodge rampage  
395       1                ford ranger  
396       1                 chevy s-10  

[248 rows x 9 columns]

In [67]:
df[ (df.origin == 1) ].describe().T

count         mean         std     min     25%     50%  \
mpg           248.0    20.071774    6.413145     9.0    15.0    18.5   
cylinders     248.0     6.258065    1.658598     4.0     4.0     6.0   
displacement  248.0   246.284274   98.515401    85.0   151.0   250.0   
weight        248.0  3363.250000  796.126952  1800.0  2715.0  3372.5   
acceleration  248.0    15.011694    2.734556     8.0    13.0    15.0   
year          248.0    75.584677    3.661940    70.0    73.0    75.5   
origin        248.0     1.000000    0.000000     1.0     1.0     1.0   

                   75%     max  
mpg             24.075    39.0  
cylinders        8.000     8.0  
displacement   318.000   455.0  
weight        4054.250  5140.0  
acceleration    16.750    22.2  
year            78.250    82.0  
origin           1.000     1.0

In [68]:
#. filtering out origin category 2
df[ (df.origin == 2) ]

mpg  cylinders  displacement horsepower  weight  acceleration  year  \
19   26.0          4          97.0         46    1835          20.5    70   
20   25.0          4         110.0         87    2672          17.5    70   
21   24.0          4         107.0         90    2430          14.5    70   
22   25.0          4         104.0         95    2375          17.5    70   
23   26.0          4         121.0        113    2234          12.5    70   
..    ...        ...           ...        ...     ...           ...   ...   
354  34.5          4         100.0          ?    2320          15.8    81   
359  28.1          4         141.0         80    3230          20.4    81   
360  30.7          6         145.0         76    3160          19.6    81   
374  36.0          4         105.0         74    1980          15.3    82   
393  44.0          4          97.0         52    2130          24.6    82   

     origin                          name  
19        2  volkswagen 1131 deluxe sedan  
20        2                   peugeot 504  
21        2                   audi 100 ls  
22        2                      saab 99e  
23        2                      bmw 2002  
..      ...                           ...  
354       2                   renault 18i  
359       2     peugeot 505s turbo diesel  
360       2                  volvo diesel  
374       2           volkswagen rabbit l  
393       2                     vw pickup  

[70 rows x 9 columns]

In [69]:
df[ (df.origin == 2) ].describe().T

count         mean         std     min      25%     50%  \
mpg            70.0    27.891429    6.723930    16.2    24.00    26.5   
cylinders      70.0     4.157143    0.500310     4.0     4.00     4.0   
displacement   70.0   109.142857   22.582079    68.0    92.25   104.5   
weight         70.0  2423.300000  490.043191  1825.0  2067.25  2240.0   
acceleration   70.0    16.787143    3.045687    12.2    14.50    15.7   
year           70.0    75.814286    3.469506    70.0    73.00    76.0   
origin         70.0     2.000000    0.000000     2.0     2.00     2.0   

                  75%     max  
mpg             30.65    44.3  
cylinders        4.00     6.0  
displacement   121.00   183.0  
weight        2769.75  3820.0  
acceleration    18.90    24.8  
year            79.00    82.0  
origin           2.00     2.0

In [71]:
#. The entries without a specific origin value
df[ (df.origin != 1) & (df.origin != 2) & (df.origin != 3) ]

Empty DataFrame
Columns: [mpg, cylinders, displacement, horsepower, weight, acceleration, year, origin, name]
Index: []

In [76]:
#. The entries that are not us origin nor european origin
df[ (df.origin != 1) & (df.origin != 2) ]

mpg  cylinders  displacement horsepower  weight  acceleration  year  \
14   24.0          4         113.0         95    2372          15.0    70   
18   27.0          4          97.0         88    2130          14.5    70   
29   27.0          4          97.0         88    2130          14.5    71   
31   25.0          4         113.0         95    2228          14.0    71   
53   31.0          4          71.0         65    1773          19.0    71   
..    ...        ...           ...        ...     ...           ...   ...   
381  34.0          4         108.0         70    2245          16.9    82   
382  38.0          4          91.0         67    1965          15.0    82   
383  32.0          4          91.0         67    1965          15.7    82   
384  38.0          4          91.0         67    1995          16.2    82   
389  32.0          4         144.0         96    2665          13.9    82   

     origin                   name  
14        3  toyota corona mark ii  
18        3           datsun pl510  
29        3           datsun pl510  
31        3          toyota corona  
53        3    toyota corolla 1200  
..      ...                    ...  
381       3         toyota corolla  
382       3            honda civic  
383       3     honda civic (auto)  
384       3          datsun 310 gx  
389       3       toyota celica gt  

[79 rows x 9 columns]

In [77]:
#. The non-US origin entries
df[ (df.origin == 2) | (df.origin == 3) ]

mpg  cylinders  displacement horsepower  weight  acceleration  year  \
14   24.0          4         113.0         95    2372          15.0    70   
18   27.0          4          97.0         88    2130          14.5    70   
19   26.0          4          97.0         46    1835          20.5    70   
20   25.0          4         110.0         87    2672          17.5    70   
21   24.0          4         107.0         90    2430          14.5    70   
..    ...        ...           ...        ...     ...           ...   ...   
382  38.0          4          91.0         67    1965          15.0    82   
383  32.0          4          91.0         67    1965          15.7    82   
384  38.0          4          91.0         67    1995          16.2    82   
389  32.0          4         144.0         96    2665          13.9    82   
393  44.0          4          97.0         52    2130          24.6    82   

     origin                          name  
14        3         toyota corona mark ii  
18        3                  datsun pl510  
19        2  volkswagen 1131 deluxe sedan  
20        2                   peugeot 504  
21        2                   audi 100 ls  
..      ...                           ...  
382       3                   honda civic  
383       3            honda civic (auto)  
384       3                 datsun 310 gx  
389       3              toyota celica gt  
393       2                     vw pickup  

[149 rows x 9 columns]